#! /bin/sh

#sxhkd &
#nm-applet &
#clipit &
#blueman-applet &

#bspc config external_rules_command "$(which external_rules)"

bspc monitor -d 1 2 3 4 5 6 7 8 9 

bspc config border_width        	 5
bspc config window_gap          	 15
#bspc config presel_feedback_color	 '#80ffffff'
#bspc config presel_feedback_color	'#7a7a7a'

#Wal colors
# source the colors.
source /home/nomad/.cache/wal/colors.sh

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1" 

bspc config split_ratio         	 0.52
bspc config borderless_monocle  	 true
bspc config gapless_monocle     	 true

bspc config focus_follows_pointer 	 true
bspc config pointer_modifier		 mod1

bspc rule -a Gimp desktop=^4 state=floating follow=on
bspc rule -a chromium-browser-chromium desktop=^1
bspc rule -a VirtualBox desktop=^4 state=floating follow=on
bspc rule -a feh state=floating 
bspc rule -a Screenkey manage=off
bspc rule -a pavucontrol state=floating 
bspc rule -a Deluge desktop=^3 follow=on
bspc rule -a mupdf state=floating
bspc rule -a Galculator state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a spotify desktop=^5
