#! /bin/sh

#sxhkd &
nm-applet &
clipit &
#blueman-applet &

bspc monitor -d 1 2 3 4 5 6 7 8 9 

bspc config border_width        	 1
bspc config window_gap          	 20
bspc config presel_feedback_color	 '#787878'

bspc config split_ratio         	 0.52
bspc config borderless_monocle  	 true
bspc config gapless_monocle     	 true

bspc config focus_follows_pointer 	 true
bspc config pointer_modifier		 mod1

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a chromium-browser-chromium desktop=^1
bspc rule -a VirtualBox desktop=^4 state=floating follow=on
bspc rule -a feh state=floating 
bspc rule -a Screenkey manage=off
bspc rule -a pavucontrol state=floating 
bspc rule -a Deluge desktop=^3 follow=on
bspc rule -a mupdf state=floating
bspc rule -a Galculator state=floating
bspc rule -a Pavucontrol state=floating

